# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x

# The `functions` block defines what code to deploy
functions:
  HelloWorldFunction:
    handler: app.lambdaHandler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
